from django.conf.urls import url

from .views import (
    team_list, tag_list, tag_detail, team_detail,
    TagCreate, TagUpdate, TeamCreate, NewsLinkCreate, NewsLinkDelete,
    TeamUpdate, TeamDelete, TagDelete)

urlpatterns = [
    url(r'^newslink/create/$',
        NewsLinkCreate.as_view(),
        name='organizer_newslink_create'),
    url(r'^newslink/delete/(?P<pk>\d+)/$',
        NewsLinkDelete.as_view(),
        name='organizer_newslink_delete'),
    url(r'^newslink/update/(?P<pk>\d+)/$',
        NewsLinkCreate.as_view(),
        name='organizer_newslink_create'),
    url(r'^team/$',
        team_list,
        name='organizer_team_list'),
    url(r'^team/create/$',
        TeamCreate.as_view(),
        name='organizer_team_create'),
    url(r'^team/(?P<slug>[\w\-]+)/$',
        team_detail,
        name='organizer_team_detail'),
    url(r'^team/(?P<slug>[\w\-]+)/update$',
        TeamUpdate.as_view(),
        name='organizer_team_update'),
    url(r'^team/(?P<slug>[\w\-]+)/delete$',
        TeamDelete.as_view(),
        name='organizer_team_delete'),
    url(r'^tag/$',
        tag_list,
        name='organizer_tag_list'),
     url(r'^tag/create/$',
        TagCreate.as_view(),
        name='organizer_tag_create'),
    url(r'^tag/(?P<slug>[\w\-]+)/$',
        tag_detail,
        name='organizer_tag_detail'),
    url(r'^tag/(?P<slug>[\w\-]+)/update$',
        TagUpdate.as_view(),
        name='organizer_tag_update'),
    url(r'^tag/(?P<slug>[\w\-]+)/delete$',
        TagDelete.as_view(),
        name='organizer_tag_delete'),
    
]