# Generated by Django 3.1.7 on 2021-03-02 15:17

from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='teams',
            field=models.ManyToManyField(related_name='blog_posts', to='organizer.Team', blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='blog_posts', to='organizer.Tag', blank=True),
        ),
    ]