# Generated by Django 3.1.7 on 2021-03-02 14:36

from __future__ import unicode_literals

from datetime import date

from django.db import migrations, models

NEWSLINKS = [
    {
        "title": "Redundant Homepage Link",
        "link": "http://jambonsw.com",
        "pub_date": date(2013, 1, 18),
        "team": 'jambon-software',
    },
    {
        "title": "Monkey (Wikipedia)",
        "link": "https://en.wikipedia.org/wiki/Monkey",
        "pub_date": date(2012, 7, 22),
        "team": "monkey-software",
    },
    {
        "title": "William Shakespeare (Wikipedia)",
        "link": "https://en.wikipedia.org/wiki/William_Shakespeare",
        "pub_date": date(2014, 4, 26),
        "team": "monkey-software",
    },
]


def add_newslink_data(apps, schema_editor):
    NewsLink = apps.get_model(
        'organizer', 'NewsLink')
    Team = apps.get_model(
        'organizer', 'Team')
    for newslink_dict in NEWSLINKS:
        newslink = NewsLink.objects.create(
            title=newslink_dict['title'],
            link=newslink_dict['link'],
            pub_date=newslink_dict['pub_date'],
            team=Team.objects.get(
                slug=newslink_dict['team']))


def remove_newslink_data(apps, schema_editor):
    NewsLink = apps.get_model(
        'organizer', 'NewsLink')
    Team = apps.get_model(
        'organizer', 'Team')
    for newslink_dict in NEWSLINKS:
        newslink = NewsLink.objects.get(
            title=newslink_dict['title'],
            link=newslink_dict['link'],
            pub_date=newslink_dict['pub_date'],
            team=Team.objects.get(
                slug=newslink_dict['team']),
        )
        newslink.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_team_data'),
    ]

    operations = [
        migrations.RunPython(
            add_newslink_data,
            remove_newslink_data)
    ]