# Generated by Django 3.1.7 on 2021-03-02 15:17

from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_newslink_unique_together_slug_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tags',
            field=models.ManyToManyField(to='organizer.Tag', blank=True),
        ),
    ]